### ISSUE TITLE
Simplify parsers

### ISSUE THREAD

**Issue by Citymonstret** [Incendo/cloud#504]
As of Cloud 2.0 we've committed to simplifying the creation of new arguments/parsers. 

Steps:
- [x] Move requirements out of arguments (#489)
- [x] Move default values out of arguments (#489)
- [x] Move from input queue to command input (#498)
- [x] Move default descriptions out of the argument
- [x] Move argument name out of the argument
- [x] Merge argument and parser

The end goal is to get rid of the argument classes entirely and leave us with parsers and builders for the parsers. Cloud already allows you to construct commands with generic arguments wrapping parsers (that's how annotated commands work) so having the extra boilerplating of per-parser command arguments doesn't serve any good purpose.
